version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: hashgo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=hashgo

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: hashgo-server
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/hashgo
      - PORT=3001
      - NODE_ENV=production
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      - mongodb

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: hashgo-client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongodb_data:
    driver: local 